export const products = [
  {
    id: 1,
    name: "Royal Cheese Burger with extra fries",
    description: "1 McChicken™, 1 French Fries, 1 Drink",
    price: 120,
    currency: "GBP",
    type: "burgers",
        image: "./assets/burger/b6.png",

   
  },
  {
    id: 2,
    name: "The classics for 3",
    description: "3 McChicken™, 3 French Fries, 3 Drinks",
    price: 360,
    currency: "GBP",
    type: "burgers",
    image: "./assets/burger/b1.png",

  },
  {
    id: 3,
    name: "The classics for 4",
    description: "4 McChicken™, 4 French Fries, 4 Drinks",
    price: 480,
    currency: "GBP",
    type: "burgers",
    image: "./assets/burger/b2.png",
  },
  {
    id: 4,
    name: "Vegetarian Burger",
    description: "1 Veggie Burger, 1 French Fries, 1 Drink",
    price: 100,
    currency: "GBP",
    type: "burgers",
        image: "./assets/burger/b3.png",

    
  },
    {
    id: 5,
    name: "Double Cheeseburger Deluxe",
    description: "2 Patties with Double Cheese, Lettuce & Tomato",
    price: 150,
    currency: "GBP",
    type: "burgers",
    image: "./assets/burger/b4.png",
  },
    {
    id: 6,
    name: "Spicy Crispy Burger",
    description: "Crispy Patty with Spicy Sauce & Jalapeños",
    price: 130,
    currency: "GBP",
    type: "burgers",
    image: "./assets/burger/b5.png",
  },
  {
    id: 7,
    name: "Standard Fries",
    description: "Medium French Fries",
    price: 30,
    currency: "GBP",
    type: "fries",
    image: "./assets/Fries/f1.png",
  },
  {
    id: 8,
    name: "Large Fries",
    description: "Large French Fries",
    price: 50,
    currency: "GBP",
    type: "fries",
    image: "./assets/Fries/f2.png",
  },



  {
    id: 11,
    name: "Seasoned Fries",
    description: "Medium Seasoned French Fries",
    price: 35,
    currency: "GBP",
    type: "fries",
    image: "./assets/Fries/f3.png",
  },
  {
    id: 12,
    name: "Extra Crispy Fries",
    description: "Large Extra Crispy Fries",
    price: 55,
    currency: "GBP",
    type: "fries",
    image: "./assets/Fries/f4.png",
  },
  {
    id: 13,
    name: "Curly Fries",
    description: "Medium Curly Fries",
    price: 40,
    currency: "GBP",
    type: "fries",
    image: "./assets/Fries/f5.png",
  },
  {
    id: 14,
    name: "Spicy Fries",
    description: "Large Spicy Fries with Chili Powder",
    price: 60,
    currency: "GBP",
    type: "fries",
    image: "./assets/Fries/f6.png",
  },
    {
    id: 9,
    name: "Coca Cola",
    description: "Medium Coca Cola",
    price: 20,
    currency: "GBP",
    type: "cold drinks",
    image: "./assets/cold/c1.png",
  },
  {
    id: 10,
    name: "Fanta",
    description: "Medium Fanta",
    price: 20,
    currency: "GBP",
    type: "cold drinks",
    image: "./assets/cold/c2.png",
  },
  {
    id: 15,
    name: "Sprite",
    description: "Medium Sprite",
    price: 20,
    currency: "GBP",
    type: "cold drinks",
    image: "./assets/cold/c3.png",
  },
  {
    id: 16,
    name: "7Up",
    description: "Medium 7Up",
    price: 20,
    currency: "GBP",
    type: "cold drinks",
    image: "./assets/cold/c4.png",
  },
  {
    id: 17,
    name: "Iced Tea",
    description: "Large Iced Tea",
    price: 25,
    currency: "GBP",
    type: "cold drinks",
    image: "./assets/cold/c5.png",
  
  },
  {
    id: 18,
    name: "Lemonade",
    description: "Large Fresh Lemonade",
    price: 25,
    currency: "GBP",
    type: "cold drinks",
    image: "./assets/cold/c6.png",
  },
];

export const reviews = [
  {
    id: 1,
    name: "St Glx",
    location: "South London",
    date: "24th September, 2023",
    rating: 5,
    image: "./assets/Ellipse.png",
    text: "The positive aspect was undoubtedly the efficiency of the service. The queue moved quickly, the staff was friendly, and the food was hot and well-packaged.",
  },
  {
    id: 2,
    name: "St Glx",
    location: "South London",
    date: "24th September, 2023",
    rating: 5,
    image: "./assets/Ellipse.png",
    text: "The positive aspect was undoubtedly the efficiency of the service. The queue moved quickly, the staff was friendly, and the food was hot and well-packaged.",
  },
  {
    id: 3,
    name: "St Glx",
    location: "South London",
    date: "24th September, 2023",
    rating: 5,
    image: "./assets/Ellipse.png",
    text: "The positive aspect was undoubtedly the efficiency of the service. The queue moved quickly, the staff was friendly, and the food was up to the usual McDonald's standard – hot and satisfying.",
  },
  {
    id: 4,
    name: "St Glx",
    location: "South London",
    date: "24th September, 2023",
    rating: 5,
    image: "./assets/Ellipse.png",
    text: "The positive aspect was undoubtedly the efficiency of the service. The queue moved quickly, the staff was friendly, and the food was up to the usual McDonald's standard – hot and satisfying.",
  },
  {
    id: 5,
    name: "St Glx",
    location: "South London",
    date: "24th September, 2023",
    rating: 5,
    image: "./assets/Ellipse.png",
    text: "The positive aspect was undoubtedly the efficiency of the service. The queue moved quickly, the staff was friendly, and the food was up to the usual McDonald's standard – hot and satisfying.",
  },
  {
    id: 6,
    name: "St Glx",
    location: "South London",
    date: "24th September, 2023",
    rating: 5,
    image: "./assets/Ellipse.png",
    text: "The positive aspect was undoubtedly the efficiency of the service. The queue moved quickly, the staff was friendly, and the food was up to the usual McDonald's standard – hot and satisfying.",
  },
];

export const similarRestaurants = [
  { id: 1, name: "McDonald's London", image: "../assets/resturent/1.png" },
  { id: 2, name: "Papa Johns", image: "../assets/resturent/2.png" },
  { id: 3, name: "KFC West London", image: "../assets/resturent/3.png" },
  { id: 4, name: "Texas Chicken", image: "../assets/resturent/4.png" },
  { id: 5, name: "Burger King", image: "../assets/resturent/5.png" },
  { id: 6, name: "Shaurma 1", image: "../assets/resturent/6.png" },
];